### ISSUE TITLE
New field available before plugin enabled

### ISSUE THREAD

**Issue by virgilwashere** [mtcextendee/mautic-international-phone-input-bundle#1]
Installed.
Plugins update 

 Cache clear

Made form with new field.

Plugin not enabled.

**Comment by kuzmany** [comment]
Fixed in version 1.1.3 https://github.com/mtcextendee/mautic-international-phone-input-bundle/releases/tag/1.1.3

**Comment by virgilwashere** [comment]
## testing current HEAD (1bcbcd9)

`1bcbcd9 (HEAD -> master, tag: 1.1.3, upstream/master, upstream/HEAD) Display field just if integration is published [Zdeno Kuzmany]`


- [x] The new field is **NOT** being shown in the available form field types.

- [ ] If I add a field of type 'Phone', then I'm offered international number validation.

![image](https://user-images.githubusercontent.com/4347038/66105358-9e315d80-e5fe-11e9-989b-0adbb4d464bd.png)

Nearly there!

**Comment by kuzmany** [comment]
It's core field and validation

Získať Outlook pre Android<https://aka.ms/ghei36>

________________________________
